apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - {{ .Values.virtualServiceHost }}
  http:
  - route:
    - destination:
        host: {{ .Values.virtualServiceHost }}
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - route:
    - destination:
        host: ratings
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details
  http:
  - route:
    - destination:
        host: details
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews-stable.bookinfo.svc.cluster.local
  http:
  - name: reviews
    route:
    - destination:
        host: reviews-stable.bookinfo.svc.cluster.local
        port:
          number: 9080
      weight: 100
    - destination:
        host: reviews-canary.bookinfo.svc.cluster.local
        port:
          number: 9080
      weight: 0
